### ISSUE TITLE
Apollo 2.0 version

### ISSUE THREAD

**Issue by stefanmaric** [howtographql/react-apollo#10]
I know it is still in beta, but it would be great to start playing around with v2.

So after following this tutorial, I wanted to upgrade to Apollo 2 beta but I'm having trouble to get it working.

The upgrade guide is still quite incomplete: https://github.com/apollographql/apollo-client/blob/master/Upgrade.md

If someone can get a working version of this repo with Apollo 2 beta would be great. We might keep it in a separated branch.

**Comment by nikolasburk** [comment]
Just happened 🎉
