### ISSUE TITLE
error on login

### ISSUE THREAD

**Issue by ardithastopalli** [howtographql/react-apollo#14]
when login button is clicked the following error is generated : 

`Uncaught (in promise) Error: GraphQL error: Argument 'email' expected type 'String!' but got: {email: $email, password: $password}. Reason: String value expected (line 2, column 27):
  authenticateUser(email: {email: $email, password: $password}) {
                          ^
GraphQL error: Cannot query field 'id' on type 'AuthenticateUserPayload'. (line 3, column 5):
    id
    ^
GraphQL error: Field 'authenticateUser' argument 'password' of type 'String!' is required but not provided. (line 2, column 3):
  authenticateUser(email: {email: $email, password: $password}) {
  ^
   `

**Comment by dstroot** [comment]
I am experiencing the same error.

**Comment by dstroot** [comment]
The authenticate user mutation is coded incorrectly.  Change Login.js as follows:

```js
// const AUTHENTICATE_USER_MUTATION = gql`
//   mutation AuthenticateUserMutation($email: String!, $password: String!) {
//     authenticateUser(email: {
//       email: $email,
//       password: $password
//     }) {
//       id
//       token
//     }
//   }
// `

const AUTHENTICATE_USER_MUTATION = gql`
  mutation AuthenticateUserMutation($email: String!, $password: String!) {
    authenticateUser(
      email: $email,
      password: $password
    ) {
      id
      token
    }
  }
`
```

**Comment by nikolasburk** [comment]
Hi @ardithastopalli, thanks a lot for pointing this out and sorry for the late reply! I just updated the repo and tutorial which should have fixed the issue. Please let me know if you're running into any further issues 🙂
