### ISSUE TITLE
GraphQL error: Cannot query field 'user' on type 'AuthenticateUserPayload'

### ISSUE THREAD

**Issue by toyeebgodo** [howtographql/react-apollo#19]
@nikolasburk I got the error below while I was testing things out during the "More Mutations and Updating the Store" chapter. After my votes feature worked as implemented, I decided to log out and log in again at which point I got this error. I am unable to log in with either of the two test accounts that I created and have been using since the "Authentication" chapter. Please help.

![graphql error](https://user-images.githubusercontent.com/23325937/33563787-191152e8-d919-11e7-836a-3575c4fb9816.png)

**Comment by toyeebgodo** [comment]
@nikolasburk I just experienced the error above again, please help.

**Comment by haxxorsid** [comment]
In Login.js replace:
```
const AUTHENTICATE_USER_MUTATION = gql`
    mutation AuthenticationUserMutation($email: String!, $password: String!){
        authenticateUser(email: $email, password: $password){
            token
            user {
                id
            }
        }
    }
`
```
With:

```
const AUTHENTICATE_USER_MUTATION = gql`
    mutation AuthenticationUserMutation($email: String!, $password: String!){
        authenticateUser(email: $email, password: $password){
            token
            id
        }
    }
`
```

**Comment by nikolasburk** [comment]
Thanks a lot for opening this issue @toyeebgodo and my sincere apologies for the delay! This issue should have been fixed with the latest update of the tutorial, please let me know if you're running into any further issues 🙂
