### ISSUE TITLE
Subscriptions failing

### ISSUE THREAD

**Issue by ryanking1809** [howtographql/react-apollo#2]
I cloned and installed this repo, added & pushed the following project.graphcool file, and adjusted the project id endpoints in `index.js` and the subscriptions appear to not be functioning.  

The only message in the console is:
`This method becomes deprecated in the new package graphql-transport-ws. Start using the GraphQLTransportWSClient to make queries, mutations and subscriptions over websockets.`

[project.graphcool.txt](https://github.com/howtographql/react-apollo/files/1187557/project.graphcool.txt)

**Comment by ryanking1809** [comment]
I've also tried https://github.com/graphcool-examples/freecom-tutorial/tree/master/freecom-04-final with no luck

**Comment by nikolasburk** [comment]
Thanks a lot for reporting this, I'm looking into the issue right now!

**Comment by nikolasburk** [comment]
Which version of `subscriptions-transport-ws` are you using @ryanking1809?

**Comment by ryanking1809** [comment]
I've tried both 0.8.1 & 0.7.3 on this repo. I also tried 0.5.4 on the freecom tutorial.

**Comment by ryanking1809** [comment]
react-apollo@1.4.2 on this repo, and react-apollo@0.11.2 on the freecom tutorial

**Comment by nikolasburk** [comment]
So, I just tried to reproduce the issue but the subscriptions do work for me. I commited some minor updates though - can you try and clone the repo again and confirm subscriptions are still broken for you? You can use this project ID for testing: cj5s6lcr2e1hz0160w8uapdgo

**Comment by nikolasburk** [comment]
I can also invite you as a collaborator to the Graphcool project so you can see the data in the data browser and use the Playround in the console. Let me know what your email is if you'd like that :)

**Comment by ryanking1809** [comment]
Ok that seems to work! Any idea what the issue was? Just the package versions?

**Comment by nikolasburk** [comment]
I would assume so as I really didn't change anything except for upgrading the packages... Still weird that you experienced the same issue with Freecom - I'll look into that later as well 🤔

Anyways, thanks a lot for reporting this! 🙌 Let us know if you come across any other issues :)

**Comment by ryanking1809** [comment]
Perhaps it my graphcool account? I just tried project id `cj5s3oafz8j4s0160czwp0jc1` from a previous attempt and it fails.

**Comment by ryanking1809** [comment]
Yes my project id it fails, your project id it works fine.

**Comment by marktani** [comment]
I'll reach out in Slack 🙌
