### ISSUE TITLE
Cannot find module "subscriptions-transport-ws"

### ISSUE THREAD

**Issue by toyeebgodo** [howtographql/react-apollo#20]
@nikolasburk I remember that in the legacy tutorial of howtographql you told us to install "subscriptions-transport-ws" as  our project's dependency, but you haven't told us to do that in this updated tutorial. Please find the printed screen with the error message below and a screenshot of my 'hackernews-react-apollo-updated\node_modules\apollo-link-ws\lib'

![subscriptions error 2](https://user-images.githubusercontent.com/23325937/33581122-d8b35520-d94f-11e7-9feb-a3e845c4ecf8.png)
![subscriptions error](https://user-images.githubusercontent.com/23325937/33581097-c7fc30f8-d94f-11e7-8998-e1dcf2b008ca.png)

**Comment by gc-codesnippets** [comment]
Hi @toyeebgodo! Thanks a lot for your feedback - what exactly were you doing when you hit this error? The tutorial was updated recentely to use Apollo Client 2.0 where `subscriptions-transport-ws` is replaced with [`apollo-link-ws`](https://github.com/howtographql/react-apollo/blob/master/package.json#L7). The tutorial contains all the new instructions (the video is still outdated though!).

**Comment by nikolasburk** [comment]
Hi @toyeebgodo! Thanks a lot for your feedback - what exactly were you doing when you hit this error? The tutorial was updated recentely to use Apollo Client 2.0 where `subscriptions-transport-ws` is replaced with [`apollo-link-ws`](https://github.com/howtographql/react-apollo/blob/master/package.json#L7). The tutorial contains all the new instructions (the video is still outdated though!).

**Comment by toyeebgodo** [comment]
Thanks for your response, I was strictly following the text-based tutorial and the error occurred when I decided to "yarn start" after finishing the "Realtime updates with GraphQL subscriptions" chapter.

**Comment by nikolasburk** [comment]
Ah - it might be that `apollo-link-ws` is using `subscriptions-transport-ws` under the hood. Did you try running `yarn add subscriptions-transport-ws` and adding this as a dependency? This _shouldn't_ be necessary but I think Apollo messed up parts of their dependency structure when releasing Apollo Client 2.0, so this might be a feasible workaround?!

**Comment by toyeebgodo** [comment]
@nikolasburk running " yarn add subscriptions-transport-ws" as a workaround worked. Thank you as always.
