### ISSUE TITLE
this quiz answer is incorrect

### ISSUE THREAD

**Issue by keithnorm** [howtographql/react-apollo#25]
<img src="https://www.evernote.com/shard/s154/sh/8939e9ef-4e6a-49f5-81ef-a95520be2d5b/f0085a12db3251a8/res/1924998b-e987-4217-9b0c-e802561a1f78/skitch.png?resizeSmall&width=832">

**Comment by nikolasburk** [comment]
Thanks so much for pointing this out, you're absolute right @keithnorm! And I'm glad to say that THIS WAS THE REAL TEST AND YOU PASSED! 🎉  Ok just kidding, but at least I fixed it in the tutorial now 🙂  Thanks again 🙏
