### ISSUE TITLE
Unmet peer dependency for react-apollo-starter/server

### ISSUE THREAD

**Issue by I-keep-trying** [howtographql/react-apollo#26]
OK, first of all,  this is your tutorial, right? https://www.howtographql.com/react-apollo/1-getting-started/ - if not, please ignore the following.

I'm on a Windows machine, but that did not stop me from trying the curl commands (I used Windows Subsystem for Linux - still didn't work) provided to install the Graphql server backend. I have tried three times now, scrapped and deleted the entire directory and started fresh, just to make sure I followed each instruction carefully. 

Since WSL got no results, I found the github repository and cloned it. I just now noticed that all the code snippets in the tutorial have links to the repository locations - interesting that the link to this particular location (https://github.com/howtographql/react-apollo/blob/master/hackernews-react-apollo) is leading to a 404 "page not found" right now, I could have sworn the page was available yesterday?

So here's what I did, after finding the react-apollo-starter/server repo by navigating to it from the main repo page:

1) `git clone https://github.com/howtographql/react-apollo/`
2) `cd react-apollo`
3) `cd server`
4) `yarn install`
5) `prisma deploy`

The following errors were logged on screen during step 4. 

```
warning "graphql-yoga > graphql-playground-middleware-lambda@1.4.0" has unmet peer dependency "aws-lambda@^0.1.2".warning "prisma-binding > apollo-link-http@1.3.2" has incorrect peer dependency "graphql@^0.11.0".
warning "graphql-cli > graphql-playground-middleware-express@1.5.2" has unmet peer dependency "express@^4.16.2".warning "prisma-cli > prisma-cli-core > graphql-cli > graphql-playground-middleware-express@1.4.9" has unmet peer dependency "express@^4.16.2".
```

(FWIW, and maybe this is wrong on my part, but I have both prisma and graphql installed globally, both were installed within the last couple of days.)

I went ahead and continued with `yarn dev` and tried to get as far as I could with the tutorial, but nothing works. The feed query returns no data in the database. The mutations return "Not authenticated." Even though I created a free account with Prisma and authorized it through my github account, I keep getting a  "Not authenticated" error in the CLI as soon as I connect. I did update `server/src/index.js` with the correct endpoint. I even updated prisma.yml to `disableAuth: true` but no luck. I checked every single file in the entire directory tree, (except all the 10,000 node modules) but I made sure all the dependencies are there, and it seems like it should be working, unless the hidden stuff in the bundles has caused a problem.

This may or may not have anything to do with the "unmet peer dependency," and the "not authenticated" is probably completely unrelated, but I thought you might want to know anyway. I really like your tutorial style and it looks so promising, I really want it to work!

**Comment by marktani** [comment]
Hey there, thanks for sharing your situation!
I'll inline my replies.

* > OK, first of all, this is your tutorial, right?

  Yes, this is the right place to report this issue!

* > Interesting that the link to this particular location (https://github.com/howtographql/react-apollo/blob/master/hackernews-react-apollo) is leading to a 404 "page not found" right now

  From what I see this repository (the one we are talking in right now) was last changed 12 days ago. This looks like outdated links to me, maybe you could provide a PR in [this repository](https://github.com/howtographql/howtographql) to update the links? 🙂 

* > I keep getting a "Not authenticated" error in the CLI as soon as I connect.

  You're saying you are connecting. Can you help me understand where you are connecting to? What command are you executing in your CLI to connect? Can you also share the exact error you are receiving?

  This will help us figure it out together! 🙌 

* > may not have anything to do with the "unmet peer dependency,"

  I agree, this is probably unrelated.

* > [I] tried to get as far as I could with the tutorial, but nothing works.

  Let's try to tackle one specific problem after another, "nothing works" is not pointing us in the right direction (even though it's true and it must suck for you 🙂)

* > I really like your tutorial style and it looks so promising, I really want it to work!

  We'll get you there 🚀 

Feel free to ping me [in Slack](https://slack.graph.cool) (my handle is @nilan) if you're getting stuck while answering my post.

**Comment by I-keep-trying** [comment]
> You're saying you are connecting. Can you help me understand where you are connecting to? What command are you executing in your CLI to connect? Can you also share the exact error you are receiving?

Well, sorry that came out sounding so vague. The truth is, the error showed up in the integrated terminal window in my IDE, Visual Studio Code, after entering the command in step 4, but it also showed up - not verbatim, just the "Not authenticated" part, in the app/default playground browser window when I copied the mutations into the "CreatePrismaLink" and clicked the Play button. I can see from the image, and in the description, that the results should be an ID is supposed to be returned, but instead I get "Not authenticated." 

So, I'm actually able to create a Prisma server, and it seems to be running, I even made myself a token (not sure if I should have done that, oh well, I have no idea what to do with it!) but the environment running on my machine at localhost:3000/playground cannot connect to it, or cannot authenticate, or something. 

FWIW, I googled and there are a handful of other people having the same problem _right now_, as I am writing this. The Prisma github issues pages seem to indicate there might be a bug??

**Comment by nikolasburk** [comment]
Hi @I-keep-trying, thanks so much for opening this issue! I just performed a number of updates on the repo and tutorial which I believe should fix your problems! Please let me know if you're running into any further troubles and I'll be happy to take a look 🙂
