### ISSUE TITLE
prisma deploy

### ISSUE THREAD

**Issue by developer239** [howtographql/react-apollo#27]
```
You can use the prisma CLI without having it globally installed because it's listed as a development dependency in package.json.
```
I believe this is not correct. You have to define script in `package.json` otherwise you will get `prisma: command not found`

**Comment by nikolasburk** [comment]
Thanks a lot for pointing this out @developer239, the statement was indeed incorrect. `package.json` has been updated and `prisma` is now also [listed as a script](https://github.com/howtographql/react-apollo/blob/master/server/package.json#L7) which allows to invoke it by prefixing it with yarn: `yarn prisma deploy`. 🙂
