### ISSUE TITLE
Duplicate items in LinkList

### ISSUE THREAD

**Issue by incon** [howtographql/react-apollo#28]
I was following the tutorial and had issues with subscriptions.

Tracked down my issue to be this https://github.com/graphcool/prisma/issues/1734

Now it’s firing too many events.
So now I end up with duplicate items in the `LinkList`

**Comment by nikolasburk** [comment]
Hey @incon, I updated the repo to use the latest dependencies of `graphql-yoga` and `prisma-binding`. This should have fixed the issue, please let me know if you're still running into any issues after testing the updated version  🙂

**Comment by incon** [comment]
```
ERROR: Workspace nikolas does not exist

{
  "data": {
    "generateClusterToken": null
  },
  "errors": [
    {
      "message": "Workspace nikolas does not exist",
      "locations": [
        {
          "line": 3,
          "column": 9
        }
      ],
      "path": [
        "generateClusterToken"
      ]
    }
  ],
  "status": 200
}
```

PR to fix this issue https://github.com/howtographql/react-apollo/pull/29
