### ISSUE TITLE
updateQuery in subscriptions missing attributes ("writeToStore.js:111 Missing field __typename")

### ISSUE THREAD

**Issue by JofArnold** [howtographql/react-apollo#30]
I thought I'd write a long explanation on this one to help people searching generally for "missing field" issues.

---

The `updateQuery` here: https://github.com/howtographql/react-apollo/blob/601a0cd69ac3775b2a6893759b46d7f84c70f819/src/components/LinkList.js#L117-L130

Results in these warnings:

```
writeToStore.js:111 Missing field count in {
  "links": [
    {
      "id": "cjdw3eql80fas0181bvfr35fh",
      "url": "asd",
      "description
...
writeToStore.js:111 Missing field __typename in {
  "links": [
    {
      "id": "cjdw3eql80fas0181bvfr35fh",
      "url": "asd",
      "description
```
This is because `feed` is being manually constructed and so is missing some properties:

```
updateQuery: (previous, { subscriptionData }) => {
  const newAllLinks = [
    subscriptionData.data.newLink.node,
    ...previous.feed.links,
  ]
  const result = {
    ...previous,
    feed: {
      links: newAllLinks, <=== Here: it's only being given "links" array
    },
  }
  return result
},
```

Instead the count (which should be manually increased) and the rest of the feed properties (e.g. `__typename` which is one of the warnings above) should be included like so:

```
updateQuery: (previous, { subscriptionData }) => {
  const newAllLinks = [
    subscriptionData.data.newLink.node,
    ...previous.feed.links,
  ]
  const result = {
    ...previous,
    feed: {
      ...previous.feed,  <========= here...
      count: previous.feed.count + 1,  <====== ...and here
      links: newAllLinks,
    },
  }
  return result
},
```

**Comment by JofArnold** [comment]
Correction: it doesn't fix the refresh. I didn't realise I'd changed quite so much code! :D I'll do another PR maybe for that.

**Comment by gdad-s-river** [comment]
@JofArnold what do you mean by 

> It doesn't fix the refresh?

It seems fine to me, unless I'm missing something?

**Comment by nhuesmann** [comment]
@JofArnold Thanks so much for this! Definitely fixes the issue.

**Comment by Natex06** [comment]
Do you have any idea to fix the refresh ?

**Comment by JofArnold** [comment]
Can you remind me what the refresh problem was, @Natex06. It's been a long time and I don't remember the code or indeed what the objective was :D

**Comment by Natex06** [comment]
Well, for me the refresh problem is that eventhough I add a new Link from the playground, the page doesn't actually refresh... so the subscription does not work :)

**Comment by JofArnold** [comment]
Sorry, I wish I could remember. I've not used prisma since then and I'm not sure the tutorial is the same as when I looked at it.

You'll need to determine if a) the server's actually publishing the change b) the client is receiving it. If the client's receiving but not rendering the usual reason for this kind of bug is not updating the cache correctly (or at all); if so inspect the data you get back from the subscription and manually update the cache accordingly. Once that works you'll need to be careful when a post/upvote/whatever is sent from the client because the user will create/update an entry and then receive the data for the subscription for the same which will result in displaying posts/upvotes twice. Again, you'll have to handle that yourself by playing with the cache.

**Comment by Natex06** [comment]
Nevermind, issue fixed for unknown reason  ahah.
Anyway, thanks for your answer, which is helpful to understand better the process of a subscription :)

**Comment by jwrubel** [comment]
I ran in to this same problem and the changes suggested here fixed it. I thought at first that refresh wasn't working because new links added didn't show up at the bottom as I expected- the new links get added at the top, but on a full page refresh they show up at the bottom.

**Comment by swcarlosrj** [comment]
Thanks @JofArnold for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!
