### ISSUE TITLE
The app is not working in windows 

### ISSUE THREAD

**Issue by gvelasquez760** [howtographql/react-apollo#34]
i tried with yarn install then yarn start (server & client)

but i only can see this:

![11111](https://user-images.githubusercontent.com/5011769/36950999-f9a61e56-1fdc-11e8-904e-21f862c806d8.png)

i think something is not working

thanks!

**Comment by Giorgix** [comment]
@gvelasquez760 Everything seems to be working (if no errors on the JS console). You just have to "submit" some links after creating an account. 
I'd recommend using  the GraphQL Playground to get your hands dirty and practice queries, mutations and subscriptions. It's launched with the server, and you can access it at http://localhost:4000/ 

The app follows these tutorials:
- [Backend](https://www.howtographql.com/graphql-js/0-introduction)
- [Frontend](https://www.howtographql.com/react-apollo/0-introduction/)

**Comment by swcarlosrj** [comment]
Thanks @ctb116 for opening this issue 😄. It seems to be resolved. Closing this, please, feel free to re-open this issue if you cannot make it work!
