### ISSUE TITLE
Login with no creds

### ISSUE THREAD

**Issue by erichodges** [howtographql/react-apollo#35]
If I've been previously logged in and I log out, I can then go to the login page and click the login button, the app then logs me in with no creds.

**Comment by erichodges** [comment]
@AmoDinho  It's been a long time since I looked at this. I now assume that I had a cookie or a JWT token on my machine and that's why I was able to get back in without logging in.

**Comment by AmoDinho** [comment]
@erichodges  Cool, I will continue to work on it till I have found a work around and share it 🥇

**Comment by erichodges** [comment]
@AmoDinho I don't think there is a work around. This is often how auth is setup, so that the user does not have to log in every time. You might want to look around for when the token expires or the cookie expires.

**Comment by AmoDinho** [comment]
@erichodges You're 100% right, according to the [docs](https://www.apollographql.com/docs/react/recipes/authentication.html) it seems we would need to call `client.clearStore()` in the `onClick()`  handler of the logout button which will clear the store. Which might be another solution 🤷‍♀️

**Comment by erichodges** [comment]
@AmoDinho Ok, cool. That might be good for a logout button :-).

**Comment by swcarlosrj** [comment]
Thanks @erichodges for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!
