### ISSUE TITLE
Give valid equivalent for Windows

### ISSUE THREAD

**Issue by MisinformedDNA** [howtographql/react-apollo#39]
To [pull server components](https://www.howtographql.com/react-apollo/1-getting-started/), the following instruction is given

`curl https://codeload.github.com/howtographql/react-apollo/tar.gz/starter | tar -xz --strip=1 react-apollo-starter/server`

While `curl` will work with PowerShell 5.0 and up, `tar` does not work out of the box.

There are various tools that can be downloaded for this purpose, or we can provide an equivalent `zip` file.

**Comment by swcarlosrj** [comment]
Thanks @MisinformedDNA for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!
