### ISSUE TITLE
The orderBy createdAt_DESC is not working

### ISSUE THREAD

**Issue by arelaxend** [howtographql/react-apollo#42]
Hello people,

I found that the createdAt_DESC is not working, whereas the following is working directly on GraphQL Playground.
`query queryfeed{
  feed(orderBy:createdAt_DESC) {
    count
    links {
      id
      createdAt
    }
  }
}`

How to make it works in LinkList.js ?

**Comment by elliotaplant** [comment]
On the server, the `orderBy` parameter is not being used by the `Query` resolver for `feed` and is also not being used by the `Feed` resolver to `links`. To use the `orderBy` parameter you'll need to change both files:

```javascript
```

**Comment by KMontag42** [comment]
don't forget to change this line:
```javascript
const queriedLinks = await ctx.db.query.links({ first, skip, where })
```
to include the `orderBy` parameter as well.

otherwise your pagination will not properly skip based on the `orderBy` clause.

ie:
```javascript
const queriedLinks = await ctx.db.query.links({ first, skip, where, orderBy })
```

**Comment by elliotaplant** [comment]
Great catch @KMontag42! Thanks

**Comment by swcarlosrj** [comment]
Thanks @arelaxend for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!
