### ISSUE TITLE
Can't download server code from windows

### ISSUE THREAD

**Issue by asongdon** [howtographql/react-apollo#48]
Hi,

I'm using Windows and have Git CLI installed but got the following problem when I try to run the command:
`curl https://codeload.github.com/howtographql/react-apollo/tar.gz/starter | tar -xz --strip=1 react-apollo-starter/server`

```
% Total    % Received % Xferd  Average Speedt a r :T iEmrer o r   oTpiemnei n g   a rTcihmiev e :C uFrarielnetd
t o   o p e n   ' \ \ . \ t a p e 0 '
             Dload  Upload   Total   Spent    Left  Speed
  9  123k    9 12330    0     0  12330      0  0:00:10 --:--:--  0:00:10 22541
curl: (23) Failed writing body (0 != 12330)
```

**Comment by swcarlosrj** [comment]
Thanks @asongdon for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!
