### ISSUE TITLE
warning after creating a link

### ISSUE THREAD

**Issue by diogoalves** [howtographql/react-apollo#5]
after creating a link I'm receiveing the warning
```
Missing field votes in {
  "postedBy": {
...
```

Solved by adding votes in CreateLink.js -> CREATE_LINK_MUTATION

```
const CREATE_LINK_MUTATION = gql`
mutation CreateLinkMutation($description: String!, $url: String!, $postedById: ID!) {
  createLink(
    description: $description,
    url: $url,
    postedById: $postedById
  ) {
    id
    createdAt
    url
    description
    postedBy {
      id
      name
    }
    votes {
      id
      user {
        id
      }
    }
  }
}
`
```

**Comment by nikolasburk** [comment]
Thanks a lot for pointing this out @diogoalves, just fixed the issue with your suggestion 🙌

**Comment by grath90** [comment]
It does not seem that the tutorial was updated with this suggestion. I still get the warning and all the links say posted by unknown.
