### ISSUE TITLE
Error:Cluster undefined does not exist while running 'prisma deploy'

### ISSUE THREAD

**Issue by aravind1078** [howtographql/react-apollo#50]
i have installed prisma using the command 'npm install -g prisma' and while running the command
'prisma deploy' it is giving this error 
   `config CWD /Users/aravind/tekie/hackernews-react-apollo/server +0ms
      config HOME /Users/aravind +2ms
     config definitionDir /Users/aravind/tekie/hackernews-react-apollo/server/database +5ms
  config definitionPath /Users/aravind/tekie/hackernews-react-apollo/server/database/prisma.yml +0ms
  cli { isGlobal: true } +0ms
  StatusChecker setting status checker +0ms
  cli command id deploy +7ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/aravind/Library/Caches/prisma/plugins.json +1ms
  cli:plugincache Got plugin from cache +1ms
  cli:plugincache /Users/aravind/Library/Caches/prisma/plugins.json +0ms
  plugins findCommand prisma-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core +0ms
  portfinder:defaultHosts exports._defaultHosts is: [ '0.0.0.0', '127.0.0.1', '::1', 'fe80::1', 'fe80::18fb:a4af:2b44:3fea', '192.168.43.100', '2405:204:6209:18b0:144f:bac3:86ac:3cdf', '2405:204:6209:18b0:fd46:e3b7:952f:d569', 'fe80::1c49:3cff:fe5f:7e16', 'fe80::3e5f:ab5d:16dd:a8bf' ] +0ms
  cli-engine:plugins:manager required +538ms
  plugin required command +540ms
  StatusChecker setting status checker +569ms
Error: Cluster undefined does not exist.
    at Deploy.<anonymous> (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/src/commands/deploy/index.ts:175:13)
    at step (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/index.js:42:23)
    at Object.next (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/index.js:23:53)
    at fulfilled (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/deploy/index.js:14:58)
    at <anonymous>
  util timed out +0ms
Exiting with code: 0`
iam in server folder 
my node version: v9.11.1
prisma version: 1.8.3

**Comment by swcarlosrj** [comment]
Thanks @aravind1078 for opening this issue 😄. It seems to be a prisma related error, probably it was fixed on the newest versions. Closing this, please, feel free to re-open this issue if you cannot make it work!
