### ISSUE TITLE
Invalid Prisma endpoint provided: __PRISMA_ENDPOINT__

### ISSUE THREAD

**Issue by labike** [howtographql/react-apollo#51]
thank you tutorial !!!

in client and server, when I run `yarn start`, I get the error

 'Invalid Prisma endpoint provided: __PRISMA_ENDPOINT__' 

I try find anwser in this issues [react-fullstack-graphql/issues](https://github.com/graphql-boilerplates/react-fullstack-graphql/issues/278), but I don't know what mean?

this is my error image:

![register](http://oo8hp4ueg.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-06-02%20%E4%B8%8B%E5%8D%884.46.01.png)
![register console error](http://oo8hp4ueg.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-06-02%20%E4%B8%8B%E5%8D%884.46.30.png)
![client yarn start](http://oo8hp4ueg.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-06-02%20%E4%B8%8B%E5%8D%884.46.09.png)
![server yarn start](http://oo8hp4ueg.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-06-02%20%E4%B8%8B%E5%8D%884.46.46.png)

I need your help, thanks!

**Comment by grgzhng** [comment]
How did you fix this error?

**Comment by Gajananghuge** [comment]
I have same issue could you please help me. How did you fixed this issue
