### ISSUE TITLE
Prisma and Create React App defaults to same port (3000)

### ISSUE THREAD

**Issue by Tornskaden** [howtographql/react-apollo#53]
When starting the server via `yarn dev` and then the app via `yarn start` the later complains port 3000 is already in use.

Seems others have the same issue: https://github.com/prismagraphql/prisma/issues/1714

In the Backend section of [Getting Started](https://www.howtographql.com/react-apollo/1-getting-started/) I suggest you add a note about it.
Easy fix: Change `"playground": "graphql playground"` to `"playground": "graphql playground --port 5000"`

https://github.com/howtographql/react-apollo/blob/980e18a75b8eb89c24ea5c8798514efe0b7044d0/server/package.json#L6

Hope this is helpful to your peers.
As I am new to React, Apollo, Prisma and GraphQL it took me awhile to find out where to fix it 😉

**Comment by swcarlosrj** [comment]
Thanks @Tornskaden for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!
