### ISSUE TITLE
TypeError when updating cache after vote

### ISSUE THREAD

**Issue by corbpaul** [howtographql/react-apollo#58]
When triggering the vote mutation and the `_updateCacheAfterVote` function the console show the error:

```
TypeError: Cannot assign to read only property 'votes' of object '#<Object>'
```

This is from [More Mutations and Updating the Store](https://www.howtographql.com/react-apollo/6-more-mutations-and-updating-the-store/)

**Comment by swcarlosrj** [comment]
@corbpaul gotcha! It'd be awesome if you could create a PR with proposed solution. Tip: NEW_LINKS_SUBSCRIPTION 👀, do not hesitate to contact me if you have any questions!

**Comment by addstar34** [comment]
@corbpaul I just went through this and didn't get any errors but the votes count doesn't increase unless I refresh the page or change the route by clicking 'submit' and then back to 'new'. Did you get this issue fixed?

**Comment by FernandoBasso** [comment]
I have the same problem.

```javascript
class LinkList extends Component {
  _updateCacheAfterVote = (store, createVote, linkId) => {
    const data = store.readQuery({ query: FEED_QUERY });

    const votedLink = data.feed.links.find(link => link.id === linkId);
    votedLink.votes = createVote.link.votes;

    store.writeQuery({
      query: FEED_QUERY,
      data,
    });
    console.log(data);
  };
  // rest of LinkList class
}
```

The `console.log(data)` line shows the correct number of votes after a vote, but the UI _won't_ rerender.

**Comment by vogelino** [comment]
Same here! No vote update. I don't have this problem with the update function of the createLink.js Mutation though... 🤔

**Comment by swcarlosrj** [comment]
Thanks @corbpaul for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!
