### ISSUE TITLE
Adding new links after implementing pagination causes issues with the subscription

### ISSUE THREAD

**Issue by ChristianIvicevic** [howtographql/react-apollo#64]
I just finished the tutorial on the page and noticed that pagination is causing some issues. Once implemented, new links that get submitted are not automatically appearing in the list unless the page is fully refreshed. Surprisingly enough in another window those get automatically added via the subscriptions regardless.

My assumption is that the local cache is not invalidated after adding a new link in the first place. Can anyone confirm this odd behaviour?

**Comment by swcarlosrj** [comment]
Thanks @ChristianIvicevic for opening this issue 😄. That's the current behaviour to not over complicate the tutorial. Closing this!
