### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by b33son** [howtographql/react-apollo#65]
The documentation and the examples show getting the an auth token from localstorage like this:

https://github.com/howtographql/react-apollo/blob/master/src/index.js

```
const authLink = setContext((_, { headers }) => {
  const token = localStorage.getItem(AUTH_TOKEN)
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : '',
    },
  }
})
```

 const token = localStorage.getItem(AUTH_TOKEN) returns a promise. So, I'm unable to use it like this. To make it work, I have to wait for it to resolve. 

```
const authLink = setContext(async (_, { headers }) => {
  const token = await localStorage.getItem(AUTH_TOKEN)
  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : '',
    },
  }
})
```

Caused me some headache. I'm not sure if I'm doing something else wrong, or if the documentation is out of date.

**Comment by swcarlosrj** [comment]
Thanks @b33son for opening this issue 😄. It should be working now with the latest docs. Closing this, please, feel free to re-open this issue if you cannot make it work!
