### ISSUE TITLE
Confusing instructions regarding Prisma server

### ISSUE THREAD

**Issue by jmargolisvt** [howtographql/react-apollo#68]
When I get to this step:

> When the browser opens, register with Prisma Cloud and go back to your terminal.

there is no option to register.  Only a button that says "Grant Permission" which then yields the error:

> Network error: Unexpected token < in JSON at position 0

After quite some time trying to figure this out, I realize that the problem is that the instructions are unclear.  Running the `yarn prisma deploy` command opens a tab in the browser which the instructions indicate contains a place to register.  Instead you are presented with only one option which errors.

Please make the docs more clear.  Something like: 

> Visit http://app.prisma.io and create an account.  After you have completed registration, run the `yarn prisma deploy` command.

Still, after deciphering that much, I'm still stuck with 
```
/Users/workjeff/Apps/hackernews-react-apollo/server/src/index.js:23
    ...request,
    ^^^
SyntaxError: Unexpected token ...
```
Any ideas how to get past this now?

**Comment by ebitsdev** [comment]
Thanks for the above comment recommending to add the instructions:

> Visit http://app.prisma.io and create an account. After you have completed registration, run the yarn prisma deploy command.

I was able to get the deployment completed after reading the suggestion.

**Comment by swcarlosrj** [comment]
Thanks @jmargolisvt for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!
