### ISSUE TITLE
GraphQL: Getting Started - Error: Field 'count' of type 'Int' must not have a sub selection.

### ISSUE THREAD

**Issue by ctb116** [howtographql/react-apollo#71]
Hi,

I'm going through the GraphQL tutorial with React-Apollo and I'm facing an issue in the [ Getting Started section](https://www.howtographql.com/react-apollo/1-getting-started/
).

I successfully deployed my prisma server and can see the Playground on my localhost: 4000.

I then copy the following mutation to the left pane of the Playground:

```
mutation {
  prismaLink: post(
    description: "Prisma replaces traditional ORMs and makes it easy to build GraphQL servers 😎",
    url: "https://www.prisma.io"
  ) {
    id
  }
  apolloLink: post(
    description: "The best GraphQL client for React",
    url: "https://www.apollographql.com/docs/react/"
  ) {
    id
  }
}
```
To verify the mutation works I replace everything in the left pan with the following query:
```
{
  feed {
    links {
      id
      description
      url
    }
  }
}
```
According the the tutorial, what I should see is this:

```
{
  "data": {
    "feed": {
      "links": [
        {
          "id": "cjcnfwjeif1rx012483nh6utk",
          "description": "The best GraphQL client",
          "url": "https://www.apollographql.com/docs/react/"
        },
        {
          "id": "cjcnfznzff1w601247iili50x",
          "description": "Prisma replaces traditional ORMs and makes it easy to build GraphQL servers 😎",
          "url": "https://www.prisma.io"
        }
      ]
    }
  }
}
```

This is the error I see instead: 

```
{
  "data": null,
  "errors": [
    {
      "message": "Field 'count' of type 'Int' must not have a sub selection. (line 4, column 7):\n      count {\n      ^",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "feed"
      ]
    }
  ]
}
```

I continued on with the tutorial and set up React following instructions in [Queries](https://www.howtographql.com/react-apollo/2-queries-loading-links/) However the same error occurred in the terminal.

```
Server is running on http://localhost:4000
Error: Field 'count' of type 'Int' must not have a sub selection. (line 4, column 7):
      count {
      ^
```

I've just started using GraphQL so I am not sure where to start with this problem. I did use npm whereas the tutorial uses yarn.

Any help is greatly appreciated!

**Comment by timdp** [comment]
I think this might be prisma/prisma#3919?

**Comment by swcarlosrj** [comment]
Thanks @ctb116 for opening this issue 😄. It should be working now. Closing this, please, feel free to re-open this issue if you cannot make it work!
