### ISSUE TITLE
Sending Mutations

### ISSUE THREAD

**Issue by darknight1983** [howtographql/react-apollo#72]
I wanted to post this snippet of code to see if anyone could help me understand what is going on with this particular mutation. Whats confusing me is that I don't understand what is the proper way to send a mutation. In the example below, two mutations are being sent to the GraphQL server, one using prismaLink and one using apolloLink. My question is can I use both to send mutations or do I have to use both to send a single mutation. This may be a silly question but it has me confused.

Ill take any insight on the topic. 

`mutation {
  prismaLink: post(
    description: "Prisma replaces traditional ORMs and makes it easy to build GraphQL servers 😎",
    url: "https://www.prisma.io"
  ) {
    id
  }
  apolloLink: post(
    description: "The best GraphQL client for React",
    url: "https://www.apollographql.com/docs/react/"
  ) {
    id
  }
}`

**Comment by swcarlosrj** [comment]
Thanks @darknight1983 for opening this issue 😄. `prismaLink` & `apolloLink` are just names for those mutations. Closing this for now, please, feel free to re-open it if you have any further question!
