### ISSUE TITLE
graphcool setup?

### ISSUE THREAD

**Issue by johnreynolds** [howtographql/react-apollo#8]
Likely a stupid question, but do I need to set up graphcool separately as you describe in the tutorial?

**Comment by stefanmaric** [comment]
@johnreynolds seems so, they don't provide a public project to connect to.

I wanted to test the repo as it is and I was wondering the same. I ended up following the tutorial.

If you want to shortcut a bit:

After creating the project in Graphcool with:

```shell
graphcool init --schema https://graphqlbin.com/hn-starter.graphql --name Hackernews
```

Replace the contents of your local `project.graphcool` with this (without touching the first two lines):

```graphql
type Link implements Node {
  createdAt: DateTime!
  description: String!
  id: ID! @isUnique
  updatedAt: DateTime!
  url: String!
  postedBy: User @relation(name: "UsersLinks")
  votes: [Vote!]! @relation(name: "VotesOnLink")
}

type File implements Node {
  contentType: String!
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  secret: String! @isUnique
  size: Int!
  updatedAt: DateTime!
  url: String! @isUnique
}

type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  email: String @isUnique
  updatedAt: DateTime!
  name: String!
  password: String
  links: [Link!]! @relation(name: "UsersLinks")
  votes: [Vote!]! @relation(name: "UsersVotes")
}

type Vote implements Node {
  id: ID! @isUnique
  user: User! @relation(name: "UsersVotes")
  link: Link! @relation(name: "VotesOnLink")
}
```

And then enable the Email&Password provider on Graphcool Console as described [in this chapter](https://www.howtographql.com/react-apollo/5-authentication/).

**Comment by nikolasburk** [comment]
Hi @johnreynolds! In theory you can build the GraphQL server yourself, e.g. by following one of the backend tutorials on [How to GraphQL](https://www.howtographql.com).

However, it's definitely recommended to just use the Graphcool Framework for the tutorial since it saves you a lot of time you'd otherwise spend on the backend! 👍
