### ISSUE TITLE
Update store in vote mutation not updating votes in the UI. 

### ISSUE THREAD

**Issue by thelovesmith** [howtographql/react-apollo#83]
Hello, Good afternoon. 

I am trying to finish the  Reat-apollo tutorial but I am stuck on the Mutations and Caching section. I have everything set up correctly to my understanding, however, the new vote s will not update on the UI once you click the button. The updateStoreAfterVote function is hitting and the votes are being logged in the database but you HAVE to refresh the page just to see the updated votes for each site. 

I deleted and rewrote everything, updated my modules, and I still can not figure out my it won't update the UI. 

I'm really not sure what I'm doing wrong but any help would be greatly appreciated I would love to get this tutorial finished and expand my Graphql skills even more. Below is the link to my repo. 
[My HAckernews Clone ](https://github.com/thelovesmith/hackernews-react-apollo)

**Comment by aahdahl** [comment]
the mutation component is a sibling of the div maintaining the count, i think the tutorial needs to change to make the mutation component a parent of the div - this fixes the issue:
`class Link extends Component {
  render() {
    const authToken = localStorage.getItem(AUTH_TOKEN)

    return (
      <Mutation
        mutation={VOTE_MUTATION}
        variables={{ linkId: this.props.link.id }}
        update={(store, { data: { vote } }) =>
          this.props.updateStoreAfterVote(store, vote, this.props.link.id)
        }
      >
        {voteMutation => (
          <div className="flex mt2 items-start">
            <div className="flex items-center">
              <span className="gray">{this.props.index + 1}.</span>
              {authToken && (
                <div className="ml1 gray f11" onClick={voteMutation}>
                  ▲
                </div>
              )}
            </div>
            <div className="ml1">
              <div>
                {this.props.link.description} ({this.props.link.url})
              </div>
              <div className="f6 lh-copy gray">
                {this.props.link.votes.length} votes | by{' '}
                {this.props.link.postedBy
                  ? this.props.link.postedBy.name
                  : 'Unknown'}{' '}
                {timeDifferenceForDate(this.props.link.createdAt)}
              </div>
            </div>
          </div>
        )}
      </Mutation>
    )
  }
}`

**Comment by thelovesmith** [comment]
Thank you I will get on this ASAP.

**Comment by kwoxer** [comment]
Hey this is a good fix. Please add the change. Simple move of code lines.
