### ISSUE TITLE
hey I keep getting an error at episode 9, that network interfaceWithSubcriptions is not a a function

### ISSUE THREAD

**Issue by Oneted11** [howtographql/react-apollo#9]
![image](https://user-images.githubusercontent.com/17639178/31042743-663c8e9c-a5b7-11e7-8321-6a823c8c6402.png)
 at the console it also refuses the subscriptions connection

**Comment by nikolasburk** [comment]
Hi @Oneted11! This is fixed now with the upgrade to Apollo Client 2.0 🙌
